### ISSUE TITLE
Rework navigation articles

### ISSUE THREAD

**Issue by MartoYankov** [NativeScript/docs-v7#1375]
### Please, tell us what's the problem?
[ ] A typo
[ ] Wrong documentation
[x] Improvement of existing article
[x] Missing documentation
[x] New article needed

### Please, tell us more details
I think the current navigation articles are a bit outdated in terms of the ways you can construct your application navigation. One of the major features of {N} 4.0 was that now you can implement a lot more mobile navigation patterns (from a technical point of view, this was that the root of your app was no longer a set in stone Frame). This is not properly reflected in the navigation articles. I think it's time to update them. On top of that these articles are a bit bloated and messy. Here is my proposal:

**Core:**
- [ ] **Create a new article `Application Architecture` (ng already has it)**
 - app bootstrap - application.run/start (move from navigation article)
 - the basics of modules - xml, css, view-model
 - root, page and fragment and module name endings
 - supporting multiple screens (move from navigation article)
 - ...

- [x] **Create a new `Page` article under UI Widgets** @NickIliev 
 - Move all relevant info from navigation article
 - Create page in XML/Code
 - Get reference to a Page
 - Connection to `ActionBar`
 - Page navigation events
 - ...

- [x] Create a new `Frame` article under UI Widgets **@NickIliev** IN PROGRESS
 - Move all relevant info from navigation article
 - Create frame in XML/Code
 - Get reference to a Frame
 - Connection to `ActionBar`
 - ... there is a lot of info about the Frame in the navigation article

- [ ] **Rename the `Modal Page` article to `Modal View` and move it out of UI Widgets** @tsonevn 
 - In general in all articles we should stop using `Modal Page` as from 4.0+ we open a modal that has a root and the developer has a choice whether to show a Frame -> Page or not.
 - Rework the article and examples, so that we make the new post 4.0 approach more visible.

- [ ] **Tweak the `TabView` article in UI Widgets, so that it's more visible that it is a navigation control.**

- [ ] **Rework and Rename the `Navigation` article in Core Concepts**
 - This article should explain on a higher level how the different navigation components work together to implement the application's navigation architecture.
 - I think a good inspiration can be the [Material - Understanding Navigation](https://material.io/design/navigation/understanding-navigation.html) article.
 - Forward navigation (also hierarchical) - Frame, Page - Nesting for 5.0 release.
 - Backward navigation - hierarchical: Frame, Page - chronological - implement yourself
 - Lateral navigation - Modal View, TabView, RadSideDrawer
 - Example scenarios

**TODO:** Figure out how to provide the same high level navigation architecture message in Angular.
