### ISSUE TITLE
[Tracking] Documentation Updates

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/docs-v7#1755]
### Please, tell us what's the problem?
[x] Wrong documentation
[x] Improvement of existing article
[x] Missing documentation
[x] New article needed

### Please, tell us more details

- [x] Rename UI Widgets to “Components” @tsonevn 
- [ ] Align all UI Widgets examples (following the suggestions in point 2 in the revamp document)
Each component in the section should have the following sub-sections @tsonevn, @NickIliev :
        - **_Usage_** (Screenshot)
        - **_Styling_**
                 (optional) subsection "Specific Styling Properties" (markdown table only)
        - **_Tips & Tricks_** (optional)
        Git branch (?)
        - **_Properties_** (markdown tables **only** - [like in nativescript-vue](https://nativescript-vue.org/en/docs/elements/components/button/))
        - **_Events_** (markdown tables **only** - [like in nativescript-vue](https://nativescript-vue.org/en/docs/elements/components/button/))
        - **_API Reference_** (to classes, interfaces, properties, events) 
(markdown tables **only** - [like in nativescript-vue](https://nativescript-vue.org/en/docs/elements/components/button/))
        - **_Native Source_** (e.g., android.widget.Button & UIButton) 
(markdown tables **only** - [like in nativescript-vue](https://nativescript-vue.org/en/docs/elements/components/button/))
        - **_See more_**

Test example that implements the above structure is created [here](https://github.com/NativeScript/nativescript-sdk-examples-ng/tree/niliev/ui-revamp/app/ng-ui-widgets-category/button)

- [x] Move modal view to Components @tsonevn 
- [x] Move Pro UI to Components @tsonevn 
- [ ] Within User Interface create a “Styling” section and move “Styling” and “Theme”
- [x] Remove the “Common Screens” section from App & Screens @tsonevn 
- [ ] Remove “Transpilers”
- [ ] Move “Change App ID” to “Publishing” @tsonevn 
- [ ] Sync with CLI team about the CLI section
- [ ] Release section - revise the whole section!
- [ ] Plugin development meeting with the Plugin team
- [x] Deleting the “Hardware Access” section @tsonevn 
- [ ] After removing a section check the NGIX redirects @tsonevn 
- [ ] Create custom 404 / 500  pages @tsonevn 
- [ ] Replace templates in App Screens with the Marketplace templates
- [ ] “Create your own templates” section needs an update (check for duplicate guidelines)
- [ ] Talk with @bundyo  about “ Improve this Article” (the scrolling bug with the side scroll and visibility)
- [ ] Remove “How to make the app fast with Android”
- [ ] Create a meeting with the runtimes teams about the Android Runtime iOS runtime sections

**Comment by NickIliev** [comment]
Re-vamped UI widgest in Angular && SDK-JS apps so far:
- [x] ActionBar
- [x] ActivityIndicator
- [x] BottomNavigation
- [x] Button
- [x] DatePicker
- [x] Tabs

**Comment by NickIliev** [comment]
Re-vamped UI widgest in Angular && SDK-JS apps
- [x] Dialogs
- [x] Gestures
- [x] FormattedString
- [x] HtmlView

**Comment by NickIliev** [comment]
Re-vamped UI widgest in Angular && SDK-JS apps
- [x] Image
- [x] ListPicker
- [x] Label

**Comment by vchimev** [comment]
> - [ ] Within User Interface create a “Styling” section and move “Styling” and “Theme”

As the " Styling" article is bulky, I'd suggest it split to sub-articles.

**Comment by NickIliev** [comment]
Re-vamped UI components in Angular app
- [x] Progress
- [x] ScrollView
- [x] Slider
- [x] Switch
- [x] TabView
- [x] TextField

**Comment by NickIliev** [comment]
NativeScript Angular && JS examples
- [x] application-settings
- [x] color
- [x] connectivity
- [x] file-system
- [x] fps-meter
- [x] http
- [x] platform

JS examples
- [x] console
- [x] fetch
