### ISSUE TITLE
Feedback form

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/docs-v7#995]
- [x]  NS + NS Angular example - how to use `toBase64String` method - https://docs.nativescript.org/cookbook/image-source - done via [https://github.com/NativeScript/NativeScript/pull/5390](https://github.com/NativeScript/NativeScript/pull/5390) and via [https://github.com/NativeScript/nativescript-sdk-examples-ng/pull/265](https://github.com/NativeScript/nativescript-sdk-examples-ng/pull/265)

- [x] extended example of how to change the Activity Indicator state on receiving data from HTTP request (NS + NS Angular example) **(in progress)**

- [x]  providing a description how the [imageSource module](https://docs.nativescript.org/cookbook/image-source) and it's methods works.

- [x] creating sample non-Angular app, which provides some use case examples- similar to [nativescript-sdk-examples-ng](https://github.com/NativeScript/nativescript-sdk-examples-ng/tree/master/app)

- [x] [example ](https://docs.nativescript.org/cookbook/ui/frame) how to use the `BackstackEntry` option.

- [x] Improve the **ListView** example snippets in the documentation - related to [https://github.com/NativeScript/docs/issues/981](https://github.com/NativeScript/docs/issues/981)

- [x] Improve the **TabView** example snippets in the documentation - https://docs.nativescript.org/cookbook/ui/tab-view

- [x] Improve the **TextField** example for N + Angular (sdk examples) - related to [https://github.com/NativeScript/docs/issues/987](https://github.com/NativeScript/docs/issues/987)
Resolved via [https://github.com/NativeScript/nativescript-sdk-examples-ng/pull/260](https://github.com/NativeScript/nativescript-sdk-examples-ng/pull/260)

- [x] improve **Switch** examples [https://docs.nativescript.org/cookbook/ui/switch](https://docs.nativescript.org/cookbook/ui/switch)

- [x] improve the **GridLayout** examples [https://docs.nativescript.org/cookbook/ui/layouts/grid-layout](https://docs.nativescript.org/cookbook/ui/layouts/grid-layout)

- [x] improve the **WrapLayout** examples [https://docs.nativescript.org/cookbook/ui/layouts/wrap-layout](https://docs.nativescript.org/cookbook/ui/layouts/wrap-layout)

- [ ] Research - what are the available options for providing live demo inside the documentation

- [x] providing sample project for the [Multithreading Model article](https://docs.nativescript.org/core-concepts/multithreading-model)
- [ ]  ability to open the feedback form on second time after closing without leaving a comment in the first time
- [x] validate if the code snippets in the List View article are up to date - https://docs.nativescript.org/angular/ui/list-view 

- [x] provide more examples, which shows, how the **Property System** works in NativeScript [https://docs.nativescript.org/core-concepts/properties](https://docs.nativescript.org/core-concepts/properties) @NickIliev resolved via [https://github.com/NativeScript/docs/pull/1291](https://github.com/NativeScript/docs/pull/1291)

- [x] ActionBar NavigationButton for iOS documentation sections says that:
    > The default text of the button is the title of the previous page; you can change it by setting the text 
    property as shown in the example Setting the Text Title.

    In fact, only the back arrow will be rendered if not text is provided - test and improve the article section

- [x] extending the **ActionBar** examples (providing usecase example) [https://docs.nativescript.org/cookbook/ui/action-bar](https://docs.nativescript.org/cookbook/ui/action-bar)

- [x] Default behaviour of [NavigationButton ](https://docs.nativescript.org/ui/action-bar#navigation-button)on Android - clarify that there is no default behavior @tsonevn 

- [x] Add section explaining `getViewByID` in[ this documentation section](https://docs.nativescript.org/core-concepts/properties#iterating-over-view-children)
Rersolved via [https://github.com/NativeScript/docs/pull/1056](https://github.com/NativeScript/docs/pull/1056)

- [x] providing extended samples, how to set up the style of the components, while using CSS(for example Button, ...) 

- [ ] providing Screenshots for the code snippets in the Cookbook section

- [x] extending the **Timer module** examples - https://docs.nativescript.org/cookbook/timer

- [x] extending File-System article (providing more info about the folders which could be accessed in iOS and Android) - https://docs.nativescript.org/cookbook/file-system
  
- [ ] include JavaScript snippets in the article ["Property System"](https://docs.nativescript.org/core-concepts/properties)  
 
 - [x] provide additional information in [the animation examples](https://docs.nativescript.org/cookbook/ui/animation) regarding "Is the animated properties relative or absolute?"

- [x] extending the **Application Settings** examples - https://docs.nativescript.org/cookbook/application-settings

**Comment by NickIliev** [comment]
- [x] Improve [this Cookbook GridLayout article ](https://docs.nativescript.org/cookbook/ui/layouts/grid-layout)by providing links to [the GridLayout extended description](https://docs.nativescript.org/angular/ui/layout-containers#gridlayout). 

- [x] cover all examples of using `stretch` property for images [https://docs.nativescript.org/cookbook/ui/image#setting-image-stretching](https://docs.nativescript.org/cookbook/ui/image#setting-image-stretching)

- [ ] mention the extensions for creating snippets with a single command - requested via _"...Page added with single command like in ionic..."_

- [x] [data binding article](https://docs.nativescript.org/core-concepts/data-binding#basic-binding-concepts) improvement. Revise the following sentence:
```
or two-way data binding, the target property should be a dependency property.
```

- [ ] Improve the UX for the following article: [https://docs.nativescript.org/angular/ui/layout-containers](https://docs.nativescript.org/angular/ui/layout-containers) Related to tables with properties and values not rendered properly.

> The layout of my browser is terrible! I cannot differentiate the content of the Property (column) versus Description (column). They are jammed together with word wrapping around them, like a taco stuffed into a coffee cup :). Why isn't the content wider? It's so narrow for a desktop browser...!?

- [x] Improve SearchBar example description ([here](https://docs.nativescript.org/angular/code-samples/ui/search-bar)) @tsonevn 

- [x] include `originX` and `originY` examples of animations to demonstrate the properties and how to use them (to animate around own center) @NickIliev

- [x] [Article "Styling" section "Custom Fonts" ](https://docs.nativescript.org/ui/styling#custom-fonts)update the screenshot as the font names do not correspond to the class names. @tsonevn 

- [x] Add an explicit note about [debugging ](https://docs.nativescript.org/tooling/debugging#debugging)a HTTP request (no supported at this very moment with 3.4.0) @tsonevn -the debugging while using HTTP request seems to work as expected with the latest NS version 4.1

- [x] [Add a section note explaining that item template](https://docs.nativescript.org/angular/ui/list-view) should have a **single root view** as a container.
Related to [this](https://stackoverflow.com/questions/45842530/nativescript-listview-object-object) (logged from the same user in the feedback) @NickIliev resolved via [https://github.com/NativeScript/nativescript-sdk-examples-ng/pull/313](https://github.com/NativeScript/nativescript-sdk-examples-ng/pull/313)

**Comment by tsonevn** [comment]
- [x] moving the [angular-data-binding](https://docs.nativescript.org/core-concepts/angular-data-binding) article in Angular section.

**Comment by tsonevn** [comment]
- [x] extending [HTTP Module examples ](https://docs.nativescript.org/cookbook/http)("What about building a multipart/form-data POST") @tsonevn  - related to Feature Request -https://github.com/NativeScript/NativeScript/issues/59 In this case [nativescript-background-http](https://github.com/NativeScript/nativescript-background-http) can be used

- [x] extending [DatePicker examples ](https://docs.nativescript.org/cookbook/ui/date-picker)

^^^ see "Improve this article" section (DatePicker) @tsonevn

**Comment by tsonevn** [comment]
- [x] providing additional info, how to setup Android Studio in [android-virtual-devices](https://docs.nativescript.org/angular/tooling/android-virtual-devices) article

>Note: @nileiv after internal discussion on the matter, the team decided that it is best not to create extended article but redirect to the one located on the Android Studio site (as done currently)

+1  (from different feedbacks)
+1
+1
+1
+1  (from different feedbacks)

**Comment by tsonevn** [comment]
- [x] providing more info, what is the expected result after running `tns doctor` - https://docs.nativescript.org/start/ns-setup-os-x

**Comment by tsonevn** [comment]
- [x] improving and extending TimePicker examples in [NativeScript cookbook](https://docs.nativescript.org/cookbook/ui/time-picker).

**Comment by tsonevn** [comment]
- [x] providing an article, which explains, how we could change the application name for iOS and Android

**Comment by tsonevn** [comment]
- [x] improve Observable cookbook article 
* [observable](https://docs.nativescript.org/cookbook/data/observable) 
* [events](https://docs.nativescript.org/core-concepts/events)

**Comment by tsonevn** [comment]
- [x] improve code snippets in [Image Module article](https://docs.nativescript.org/ui/images)

**Comment by tsonevn** [comment]
- [x] moving the [angular-list-view](https://docs.nativescript.org/ui/list-view) article in Angular section.

**Comment by tsonevn** [comment]
- [x] extending [creating-launch-screens-android](https://docs.nativescript.org/publishing/creating-launch-screens-android) (providing an info, how to use Adaptive Icons in Android. https://github.com/NativeScript/template-blank-ts/issues/16 ) @NickIliev

**Comment by tsonevn** [comment]
- [ ] extending the [building-plugins](https://docs.nativescript.org/plugins/building-plugins) article (providing examples, how to create plugin while using iOS Framework)

**Comment by tsonevn** [comment]
- [ ] providing  section "Known issues"/"Limitations"  in the documentation @tsonevn  @NickIliev
> _When you start with a tool like nativescript - so new - you have to expect 1000 quirks. So I decided to not use it because there's no summary about the limits. Running into the limits when a project is half ready is simply not an option because it sets the whole investment at risk._

**Comment by tsonevn** [comment]
- [x] extending Repeaters examples in the [cookbook](https://docs.nativescript.org/cookbook/ui/repeater).
> _Using objects inside an array with repeater: [{title:"monday"}, {title:"tuesday"}]_

> adding examples about using nested arrays/objects
( _.. iterating over nested objects/arrays .._ )

**Comment by tsonevn** [comment]
- [x] extending the _**ScrollView**_ examples - https://docs.nativescript.org/cookbook/ui/scroll-view

**Comment by tsonevn** [comment]
- [ ] providing TypeScript non-Angular tutorial in the documentation.

**Comment by tsonevn** [comment]
- [ ] fix the link which is pointed in `here` in [Use-Native-Libraries](https://docs.nativescript.org/runtimes/ios/how-to/Use-Native-Libraries) article.
> Under static libraries the "here" links incorrectly to "https://docs.nativescript.org/plugins/plugins.html", which is using and finding plugins

**Comment by tsonevn** [comment]
- [x] improve the provided code Button's code samples in the cookbook - https://docs.nativescript.org/cookbook/ui/button

**Comment by tsonevn** [comment]
- [ ] providing info about  - will be KDB @tsonevn 
>error or long wait install problem 
https://docs.nativescript.org/angular/start/ns-setup-win

**Comment by tsonevn** [comment]
- [x]  improve the [Keyboard Type](https://docs.nativescript.org/api-reference/modules/_ui_enums_.keyboardtype) article

- [x] improve https://docs.nativescript.org/tooling/android-virtual-devices

- [ ] moving the navigation examples [Basics](https://docs.nativescript.org/ui/basics#navigate-to-a-page)  -> [Architecture and Navigation](https://docs.nativescript.org/core-concepts/navigation)

**Comment by tsonevn** [comment]
- [x] improve [progress](https://docs.nativescript.org/cookbook/ui/progress) article. (TypeScript example)

**Comment by tsonevn** [comment]
- [x] providing code samples for Angular - https://docs.nativescript.org/ui/icon-fonts @tsonevn

**Comment by tsonevn** [comment]
- [x] providing more info about the available option about the [prompt-dialog](https://docs.nativescript.org/angular/code-samples/ui/dialogs#prompt-dialog) @NickIliev

**Comment by tsonevn** [comment]
- [ ] improve [location aticle ](https://docs.nativescript.org/hardware/location)

**Comment by tsonevn** [comment]
- [x] extending [ImageSource examples](https://docs.nativescript.org/cookbook/image-source)
> Fetching images through url example needs to be a little more informative, showing how to manage the callback

**Comment by tsonevn** [comment]
- [ ] [ providing info/link](https://docs.nativescript.org/sidekick/intro/requirements), which shows how to install/upgrade NativeScript CLI @ggarabedian 
> SideKick force to update CLI, the help leads to this page and its not including the command

**Comment by tsonevn** [comment]
- [x] providing examples, demonstrating, how to handle orientation change event in non-Angular and NS Angular project

**Comment by tsonevn** [comment]
- [x] extending [fetch cookbook examples](https://docs.nativescript.org/cookbook/fetch)

**Comment by pedromorgan** [comment]
@tsonevn Thanks for the list...

As a new kid on the block, I want to help with docs... and some r+D leads me here..
This is a good good list to start from..
and thats from me as an non professional code.. but a da job..

ATMO my feeling is that there is no real "structure" in docs..
also some "extentions are in npm", some enterprise (whatever that means) in somewhere else...and no XML rag reference.. //

handy would be api.nactivescript.org where the docs are..
tutorial.nativescript.org.. and alike...

**Comment by pedromorgan** [comment]
More of the example tabs.. ie js, ts, ng, vue is possible .. same cat, we just skin different ways..

Indeed what would be cool is to read same docs, and all that needs to switch is the xamples..
So a cookie with TS, would be default set the tabs to be selected, wheraes with NG etc..

**Comment by tsonevn** [comment]
- [x] providing examples of Component's specific styling properties.

**Comment by NickIliev** [comment]
- [x] Groceries tutorial chapter 6 - provide a link to utils module
https://docs.nativescript.org/tutorial/ng-chapter-6

**Comment by NickIliev** [comment]
- [x] Modal page review and update related to changes in NativeScript 4.0.
[https://docs.nativescript.org/angular/code-samples/modal-page](https://docs.nativescript.org/angular/code-samples/modal-page)

**Comment by tsonevn** [comment]
- [x] extend the [angular-navigation](https://docs.nativescript.org/angular/core-concepts/angular-navigation) examples

**Comment by tsonevn** [comment]
- [ ] extend [angular-data-binding](https://docs.nativescript.org/angular/core-concepts/angular-data-binding) examples
